Repository canonical/craft-application, pull requests merged in 2024-07, with the labels that each got.

#376 chore(merge): merge '2.9.0' into 'main'
  .github/workflows/release-publish.yaml
  craft_application/application.py
  craft_application/errors.py
  craft_application/models/base.py
  craft_application/models/constraints.py
  craft_application/models/project.py
  craft_application/services/provider.py
  craft_application/util/error_formatting.py
  docs/reference/changelog.rst
  pyproject.toml
  tests/conftest.py
  tests/unit/models/test_base.py
  tests/unit/models/test_project.py
  tests/unit/test_application.py
  tests/unit/util/test_error_formatting.py
Labels: merge

#371 docs: add howto for using partitions
  docs/howto/index.rst
  docs/howto/partitions.rst
Labels: squash

#389 build(deps): update codespell
  pyproject.toml
  tests/unit/git/test_git.py
Labels: rebase
