Repository canonical/craft-application, pull requests merged in 2025-01, with the labels that each got.

#602 tests: xfail launchpad test
  tests/integration/launchpad/test_anonymous_access.py
Labels: squash

#596 fix: do not log encoded secrets
  craft_application/application.py
  docs/reference/changelog.rst
  tests/unit/test_application.py
Labels: squash

#608 chore: merge 4.8.2 to main
  craft_application/application.py
  craft_application/models/manifest.py
  docs/reference/changelog.rst
  tests/data/manifest/session-report.json
  tests/integration/services/test_fetch.py
  tests/unit/models/test_manifest.py
  tests/unit/services/test_fetch.py
  tests/unit/test_application.py
Labels: merge

#615 fix(launchpad): use the project's privacy for repos and recipes
  craft_application/launchpad/launchpad.py
  craft_application/launchpad/models/base.py
  craft_application/launchpad/models/recipe.py
  craft_application/services/remotebuild.py
  tests/unit/launchpad/test_launchpad.py
  tests/unit/services/conftest.py
  tests/unit/services/test_remotebuild.py
Labels: squash

#623 fix: remove --status from remote-build overview
  craft_application/commands/remote.py
Labels: rebase

#624 docs: update changelog, add PR checklist item
  .github/PULL_REQUEST_TEMPLATE.md
  docs/conf.py
  docs/reference/changelog.rst
Labels: rebase
